# Generated by Django 2.1.7 on 2019-04-27 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contracting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorm_name', models.CharField(max_length=255)),
                ('room_number', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('period', models.IntegerField(default=0)),
                ('deposit', models.DecimalField(decimal_places=3, max_digits=10)),
                ('dmg_deposit', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorm_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('floor', models.IntegerField(default=0)),
                ('elecUnit', models.DecimalField(decimal_places=3, max_digits=10)),
                ('waterUnit', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.BooleanField(default=False)),
                ('emp_fname', models.CharField(max_length=255)),
                ('emp_lname', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('emp_phone', models.CharField(max_length=10, unique=True)),
                ('dorm_dorm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Dorm')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_desc', models.TextField()),
                ('price_per_unit', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_fname', models.CharField(max_length=255)),
                ('guest_lname', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('career', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('line', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField()),
                ('dorm_name', models.CharField(max_length=255)),
                ('room_number', models.IntegerField(default=0)),
                ('month_no', models.IntegerField(default=0)),
                ('rent_number', models.IntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=3, max_digits=10)),
                ('contracting_contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Contracting')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('total', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.DecimalField(decimal_places=3, max_digits=10)),
                ('expense_exp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Expense')),
                ('invoice_invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Logging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.CharField(max_length=5)),
                ('login_date', models.DateTimeField()),
                ('employee_emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname_guest', models.CharField(max_length=255)),
                ('lname_guest', models.CharField(max_length=255)),
                ('arrive_date', models.DateTimeField()),
                ('post_type', models.CharField(max_length=255)),
                ('packaging', models.CharField(max_length=255)),
                ('pickup_date', models.DateTimeField()),
                ('track_number', models.CharField(max_length=13, unique=True)),
                ('room_guest', models.CharField(max_length=10)),
                ('guest_guest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Guest')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('payment_datetime', models.DateTimeField()),
                ('bill_picture', models.ImageField(blank=True, null=True, upload_to='payments_%Y-%m-%D')),
                ('payment_confirm', models.CharField(choices=[('01', 'Unpaid'), ('02', 'Paid')], default='01', max_length=2)),
                ('invoice_invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Report_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reporting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_desc', models.TextField()),
                ('report_date', models.DateTimeField()),
                ('report_type_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Report_type')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(default=0)),
                ('room_floor', models.IntegerField(default=0)),
                ('room_rate', models.DecimalField(decimal_places=3, max_digits=10)),
                ('status', models.CharField(choices=[('01', 'Available'), ('02', 'Full'), ('03', 'Booked')], default='01', max_length=2)),
                ('room_type', models.CharField(choices=[('01', 'Fan'), ('02', 'AirCondition')], default='01', max_length=2)),
                ('dorm_dorm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Dorm')),
            ],
        ),
        migrations.AddField(
            model_name='reporting',
            name='room_room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Room'),
        ),
        migrations.AddField(
            model_name='contracting',
            name='guest_guest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Guest'),
        ),
        migrations.AddField(
            model_name='contracting',
            name='room_room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Room'),
        ),
    ]
