# Generated by Django 2.1.7 on 2019-05-04 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dorm',
            name='elec_unit',
        ),
        migrations.RemoveField(
            model_name='dorm',
            name='water_unit',
        ),
    ]
