# Generated by Django 2.2.1 on 2019-05-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_desc',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
