# Generated by Django 2.2 on 2019-05-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='month_no',
            field=models.CharField(max_length=7),
        ),
    ]
