# Generated by Django 2.2.1 on 2019-05-02 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('payment_datetime', models.DateTimeField()),
                ('bill_picture', models.ImageField(blank=True, null=True, upload_to='payments_%Y-%m-%D')),
                ('payment_confirm', models.CharField(choices=[('01', 'Unpaid'), ('02', 'Paid')], default='01', max_length=2)),
                ('payment_guest_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.Guest')),
            ],
        ),
    ]
