# Generated by Django 2.1.7 on 2019-05-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20190505_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice_detail',
            name='price',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='month_no',
            field=models.CharField(max_length=7),
        ),
    ]
