# Generated by Django 2.2 on 2019-04-30 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20190428_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dorm',
            old_name='elecUnit',
            new_name='elec_unit',
        ),
        migrations.RenameField(
            model_name='dorm',
            old_name='waterUnit',
            new_name='water_unit',
        ),
        migrations.RemoveField(
            model_name='contracting',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='logging',
            name='login_time',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='pickup_date',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='room_guest',
        ),
        migrations.AddField(
            model_name='dorm',
            name='room_amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dorm',
            name='taxid',
            field=models.CharField(default='000-000', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='dorm',
            name='tel',
            field=models.CharField(default='0000000000', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('01', 'wait_pay'), ('02', 'wait_confirm')], default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='contracting',
            name='guest_guest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.Guest'),
        ),
        migrations.AlterField(
            model_name='contracting',
            name='room_room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.Room'),
        ),
        migrations.AlterField(
            model_name='dorm',
            name='floor',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dorm_dorm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.Dorm'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='contracting_contract_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.Contracting'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='month_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='invoice_detail',
            name='expense_exp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.Expense'),
        ),
        migrations.AlterField(
            model_name='invoice_detail',
            name='invoice_invoice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.Invoice'),
        ),
        migrations.AlterField(
            model_name='logging',
            name='employee_emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.Employee'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='guest_guest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.Guest'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice_invoice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.Invoice'),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='report_type_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.Report_type'),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='room_room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='dorm_dorm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.Dorm'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_floor',
            field=models.IntegerField(default=1),
        ),
    ]
