# Generated by Django 2.2.1 on 2019-05-03 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=255)),
                ('news_content', models.TextField()),
                ('dorm_dorm_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.Dorm')),
            ],
        ),
    ]
