# Generated by Django 2.2.1 on 2019-05-01 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20190501_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='guest_guest_id',
        ),
    ]
