# Generated by Django 2.2.1 on 2019-05-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20190503_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_desc',
            field=models.TextField(null=True),
        ),
    ]
