# Generated by Django 2.2.1 on 2019-05-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20190504_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_desc',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
