# Generated by Django 2.2.1 on 2019-05-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20190504_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
